In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("student_performance_data.csv")

In [17]:
df

,StudentID,Gender,Age,StudyHoursPerWeek,AttendanceRate,GPA,Major,PartTimeJob,ExtraCurricularActivities
0,1,Male,24,37,90.75,3.47,Arts,Yes,No
1,2,Female,22,37,74.90,2.32,Education,No,No
2,3,Male,22,10,53.36,2.38,Business,No,No
3,4,Male,24,10,70.26,3.46,Science,Yes,No
4,5,Male,18,19,74.87,2.31,Education,Yes,No
...,...,...,...,...,...,...,...,...,...
495,496,Male,22,37,76.61,2.97,Science,No,No
496,497,Male,23,11,56.29,3.20,Science,No,No
497,498,Female,20,6,56.64,3.20,Science,No,Yes
498,499,Male,22,18,57.18,2.05,Business,No,Yes
499,500,Female,24,21,96.99,2.64,Engineering,No,No

In [18]:
df.isnull()

,StudentID,Gender,Age,StudyHoursPerWeek,AttendanceRate,GPA,Major,PartTimeJob,ExtraCurricularActivities
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
495,False,False,False,False,False,False,False,False,False
496,False,False,False,False,False,False,False,False,False
497,False,False,False,False,False,False,False,False,False
498,False,False,False,False,False,False,False,False,False
499,False,False,False,False,False,False,False,False,False

In [32]:
df.isnull().sum()

StudentID                    0
Gender                       0
Age                          0
StudyHoursPerWeek            0
AttendanceRate               0
GPA                          0
Major                        0
PartTimeJob                  0
ExtraCurricularActivities    0
dtype: int64

In [33]:
df.describe()

        StudentID         Age  StudyHoursPerWeek  AttendanceRate        GPA
count  500.000000  500.000000         500.000000      500.000000  500.00000
mean   250.500000   20.956000          19.876000       74.990380    2.98516
std    144.481833    2.000517          11.471347       14.565917    0.56362
min      1.000000   18.000000           1.000000       50.010000    2.00000
25%    125.750000   19.000000          10.000000       62.607500    2.48750
50%    250.500000   21.000000          20.500000       75.730000    3.00000
75%    375.250000   23.000000          30.000000       87.220000    3.48000
max    500.000000   24.000000          39.000000       99.970000    3.99000

In [37]:
df.dtypes

StudentID                      int64
Gender                        object
Age                            int64
StudyHoursPerWeek              int64
AttendanceRate               float64
GPA                          float64
Major                         object
PartTimeJob                   object
ExtraCurricularActivities     object
dtype: object

In [16]:
df["Gender"].replace({"Female":0,"Male":1}, inplace=True)

C:\Users\anike\AppData\Local\Temp\ipykernel_15468\3597203515.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Gender"].replace({"Female":0,"Male":1}, inplace=True)
C:\Users\anike\AppData\Local\Temp\ipykernel_15468\3597203515.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Gender"].replace({"Female":0,"Male":1}, inplace=True)
C:\Users\anike\AppData\Local\Temp\ipykernel_15468\3597203515.py:1: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df["Gender"].replace({"Female":0,"Male":1}, inplace=True)

In [17]:
df

,StudentID,Gender,Age,StudyHoursPerWeek,AttendanceRate,GPA,Major,PartTimeJob,ExtraCurricularActivities
0,1,1,24,37,90.75,3.47,Arts,Yes,No
1,2,0,22,37,74.90,2.32,Education,No,No
2,3,1,22,10,53.36,2.38,Business,No,No
3,4,1,24,10,70.26,3.46,Science,Yes,No
4,5,1,18,19,74.87,2.31,Education,Yes,No
...,...,...,...,...,...,...,...,...,...
495,496,1,22,37,76.61,2.97,Science,No,No
496,497,1,23,11,56.29,3.20,Science,No,No
497,498,0,20,6,56.64,3.20,Science,No,Yes
498,499,1,22,18,57.18,2.05,Business,No,Yes
499,500,0,24,21,96.99,2.64,Engineering,No,No

In [19]:
df["AttendanceRate"] = df["AttendanceRate"].astype(int)
df

,StudentID,Gender,Age,StudyHoursPerWeek,AttendanceRate,GPA,Major,PartTimeJob,ExtraCurricularActivities
0,1,1,24,37,90,3.47,Arts,Yes,No
1,2,0,22,37,74,2.32,Education,No,No
2,3,1,22,10,53,2.38,Business,No,No
3,4,1,24,10,70,3.46,Science,Yes,No
4,5,1,18,19,74,2.31,Education,Yes,No
...,...,...,...,...,...,...,...,...,...
495,496,1,22,37,76,2.97,Science,No,No
496,497,1,23,11,56,3.20,Science,No,No
497,498,0,20,6,56,3.20,Science,No,Yes
498,499,1,22,18,57,2.05,Business,No,Yes
499,500,0,24,21,96,2.64,Engineering,No,No

In [21]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
normalized_data = scaler.fit_transform(df[["GPA"]])

In [11]:
normalized_data

array([[0.73869347],
       [0.16080402],
       [0.19095477],
       [0.73366834],
       [0.15577889],
       [0.2361809 ],
       [0.96984925],
       [0.25628141],
       [0.66331658],
       [0.98492462],
       [0.37688442],
       [0.0201005 ],
       [0.24623116],
       [0.83417085],
       [0.86934673],
       [0.77386935],
       [0.11557789],
       [0.79899497],
       [0.92462312],
       [0.60301508],
       [0.94472362],
       [0.82914573],
       [0.66834171],
       [0.57788945],
       [0.35175879],
       [0.16080402],
       [0.6080402 ],
       [0.32160804],
       [0.86934673],
       [1.        ],
       [0.75376884],
       [0.09045226],
       [0.29145729],
       [0.11055276],
       [0.65326633],
       [0.76884422],
       [0.92964824],
       [0.44221106],
       [0.90452261],
       [0.88442211],
       [0.31658291],
       [0.87437186],
       [0.37688442],
       [0.29648241],
       [0.65326633],
       [0.33165829],
       [0.63316583],
       [0.61306533],
       [0.5678392 ],
       [0.38190955],
       [0.55276382],
       [0.59798995],
       [0.54773869],
       [0.44723618],
       [0.01507538],
       [0.5879397 ],
       [0.17085427],
       [0.64824121],
       [0.7638191 ],
       [0.50251256],
       [0.54271357],
       [0.95477387],
       [0.84924623],
       [0.91959799],
       [0.81909548],
       [0.11055276],
       [0.15075377],
       [0.52763819],
       [0.24623116],
       [0.47738693],
       [0.39698492],
       [0.55276382],
       [0.74874372],
       [0.71859296],
       [0.52261307],
       [0.8241206 ],
       [0.4321608 ],
       [0.89949749],
       [0.07035176],
       [0.95979899],
       [0.65829146],
       [0.38190955],
       [0.1959799 ],
       [0.48241206],
       [0.1959799 ],
       [0.16582915],
       [0.61809045],
       [0.52763819],
       [0.67336683],
       [0.93467337],
       [0.53266332],
       [0.58291457],
       [0.09045226],
       [0.72361809],
       [0.40201005],
       [0.9798995 ],
       [0.82914573],
       [0.52261307],
       [0.12562814],
       [0.86432161],
       [0.8040201 ],
       [0.18592965],
       [0.29648241],
       [0.79899497],
       [0.18592965],
       [0.92462312],
       [0.42713568],
       [0.08542714],
       [0.81909548],
       [0.37688442],
       [0.52763819],
       [0.11055276],
       [0.00502513],
       [0.64321608],
       [0.51758794],
       [0.59798995],
       [0.79899497],
       [0.64824121],
       [0.1758794 ],
       [0.36180905],
       [0.90954774],
       [0.77386935],
       [0.55778894],
       [0.25628141],
       [0.30150754],
       [0.73366834],
       [0.85427136],
       [0.67336683],
       [0.81407035],
       [0.76884422],
       [0.15075377],
       [0.42713568],
       [0.15577889],
       [0.2361809 ],
       [0.87437186],
       [0.47738693],
       [0.53768844],
       [0.18090452],
       [0.31155779],
       [0.23115578],
       [0.20603015],
       [0.64321608],
       [0.25628141],
       [0.63316583],
       [0.06030151],
       [0.14070352],
       [0.27638191],
       [0.59798995],
       [0.67839196],
       [0.44723618],
       [0.44723618],
       [0.72864322],
       [0.01507538],
       [0.34170854],
       [0.8241206 ],
       [0.6080402 ],
       [0.33668342],
       [0.90954774],
       [0.77889447],
       [0.26633166],
       [0.64824121],
       [0.59798995],
       [0.40201005],
       [0.36683417],
       [0.34673367],
       [0.61809045],
       [0.44221106],
       [0.83417085],
       [0.67336683],
       [0.07035176],
       [0.64321608],
       [0.27135678],
       [0.59798995],
       [0.68341709],
       [0.23115578],
       [0.45728643],
       [0.19095477],
       [0.05025126],
       [0.38190955],
       [0.36683417],
       [1.        ],
       [0.44723618],
       [0.33668342],
       [0.58291457],
       [0.09045226],
       [0.96482412],
       [0.63819095],
       [0.75879397],
       [0.17085427],
       [0.4120603 ],
       [0.42713568],
       [0.8241206 ],
       [0.        ],
       [0.30150754],
       [0.98492462],
       [0.47738693],
       [0.38693467],
       [0.12060302],
       [0.9798995 ],
       [0.0201005 ],
       [0.73869347],
       [0.77386935],
       [0.24623116],
       [0.67336683],
       [0.09547739],
       [0.25628141],
       [0.79396985],
       [0.86934673],
       [0.61306533],
       [0.50753769],
       [0.16080402],
       [0.06532663],
       [0.12060302],
       [0.22613065],
       [0.34170854],
       [0.38190955],
       [0.34673367],
       [0.24120603],
       [0.51256281],
       [0.82914573],
       [0.28140704],
       [0.94472362],
       [0.87939698],
       [0.16080402],
       [0.78894472],
       [0.57788945],
       [0.5678392 ],
       [0.3919598 ],
       [0.50251256],
       [0.39698492],
       [0.54271357],
       [0.63316583],
       [0.67839196],
       [0.53266332],
       [0.72361809],
       [0.14070352],
       [0.21105528],
       [0.8241206 ],
       [0.32663317],
       [0.02512563],
       [0.15577889],
       [0.22613065],
       [0.95979899],
       [0.57788945],
       [0.93969849],
       [0.57788945],
       [0.48241206],
       [0.31658291],
       [0.6080402 ],
       [0.14070352],
       [0.90452261],
       [0.83417085],
       [0.32160804],
       [0.95979899],
       [0.82914573],
       [0.66834171],
       [0.12060302],
       [0.48241206],
       [0.50753769],
       [0.2361809 ],
       [0.08040201],
       [0.77889447],
       [0.12060302],
       [0.59798995],
       [0.93969849],
       [0.87939698],
       [0.28140704],
       [0.85427136],
       [0.        ],
       [0.0201005 ],
       [0.6080402 ],
       [0.36683417],
       [0.38693467],
       [0.5678392 ],
       [0.19095477],
       [0.21105528],
       [0.48743719],
       [0.75879397],
       [0.62311558],
       [0.29648241],
       [0.4321608 ],
       [0.17085427],
       [0.07537688],
       [0.78894472],
       [0.26633166],
       [0.18090452],
       [0.69346734],
       [0.62311558],
       [0.63819095],
       [0.23115578],
       [0.2361809 ],
       [0.22110553],
       [0.1758794 ],
       [0.65829146],
       [0.85427136],
       [0.72864322],
       [0.79396985],
       [0.40703518],
       [0.65829146],
       [0.35678392],
       [0.52763819],
       [0.48241206],
       [0.1758794 ],
       [0.38693467],
       [0.96984925],
       [0.25125628],
       [0.13567839],
       [0.42211055],
       [0.79396985],
       [0.58291457],
       [0.68341709],
       [0.19095477],
       [0.62311558],
       [0.32663317],
       [0.83919598],
       [0.63316583],
       [0.20100503],
       [0.06532663],
       [0.04522613],
       [0.3718593 ],
       [0.26633166],
       [0.64824121],
       [0.50251256],
       [0.26633166],
       [0.15075377],
       [0.12562814],
       [0.86934673],
       [0.24623116],
       [0.65326633],
       [0.81407035],
       [0.61809045],
       [0.86432161],
       [0.3919598 ],
       [0.95979899],
       [0.13567839],
       [0.10050251],
       [0.66331658],
       [0.94974874],
       [0.81407035],
       [0.07537688],
       [0.28140704],
       [0.93467337],
       [0.25628141],
       [0.7839196 ],
       [0.82914573],
       [0.49748744],
       [0.38693467],
       [0.45226131],
       [0.22613065],
       [0.89447236],
       [0.45226131],
       [0.88442211],
       [0.10552764],
       [0.99497487],
       [0.44723618],
       [0.05025126],
       [0.04020101],
       [0.74874372],
       [0.66331658],
       [0.8040201 ],
       [0.10552764],
       [0.03517588],
       [0.51256281],
       [0.3919598 ],
       [0.46231156],
       [0.99497487],
       [0.97487437],
       [0.94472362],
       [0.78894472],
       [0.35678392],
       [0.4120603 ],
       [0.55276382],
       [0.83417085],
       [0.07035176],
       [0.42713568],
       [0.08542714],
       [0.51758794],
       [0.90452261],
       [0.7839196 ],
       [0.23115578],
       [0.9798995 ],
       [0.66834171],
       [0.01005025],
       [0.25628141],
       [0.26130653],
       [0.07035176],
       [0.96482412],
       [0.48241206],
       [0.89949749],
       [0.32160804],
       [0.12562814],
       [0.47738693],
       [0.11557789],
       [0.48743719],
       [0.92462312],
       [0.52261307],
       [0.61809045],
       [0.15577889],
       [0.04522613],
       [0.11055276],
       [0.60301508],
       [0.09547739],
       [0.37688442],
       [0.55276382],
       [0.3919598 ],
       [0.16582915],
       [0.27638191],
       [0.93467337],
       [0.67839196],
       [0.49748744],
       [0.01507538],
       [0.99497487],
       [0.67336683],
       [0.31658291],
       [0.88442211],
       [0.26130653],
       [0.54773869],
       [0.63819095],
       [0.22110553],
       [0.98492462],
       [0.75376884],
       [0.56281407],
       [0.18090452],
       [0.05527638],
       [0.32160804],
       [0.75879397],
       [0.27135678],
       [0.54271357],
       [0.73366834],
       [0.11055276],
       [0.68844221],
       [0.09045226],
       [0.96984925],
       [0.49246231],
       [0.15075377],
       [0.34170854],
       [0.41708543],
       [0.7638191 ],
       [0.74874372],
       [0.61306533],
       [0.10552764],
       [0.15075377],
       [0.09547739],
       [0.57788945],
       [0.87939698],
       [0.43718593],
       [0.16080402],
       [0.56281407],
       [0.81407035],
       [0.74371859],
       [0.88442211],
       [0.28140704],
       [0.1959799 ],
       [0.88442211],
       [0.66331658],
       [0.31155779],
       [0.74371859],
       [0.81909548],
       [0.61809045],
       [0.69346734],
       [0.37688442],
       [0.54271357],
       [0.52763819],
       [0.85427136],
       [0.84422111],
       [0.83919598],
       [0.01005025],
       [0.75376884],
       [0.7638191 ],
       [0.68341709],
       [0.75879397],
       [0.84422111],
       [0.47236181],
       [0.50251256],
       [0.12562814],
       [0.38693467],
       [0.64824121],
       [0.7839196 ],
       [0.2160804 ],
       [0.14070352],
       [0.66834171],
       [0.        ],
       [0.18090452],
       [0.03015075],
       [0.16582915],
       [0.18090452],
       [0.3919598 ],
       [0.40201005],
       [0.87939698],
       [0.51256281],
       [0.72864322],
       [0.10552764],
       [0.22613065],
       [0.70854271],
       [0.05527638],
       [0.48743719],
       [0.60301508],
       [0.60301508],
       [0.02512563],
       [0.32160804]])